(library
 (name catt_lsp_server)
 (libraries
  dyn
  xdg
  unix
  dune-build-info
  fiber
  chrome-trace
  ; lev
  ; lev_fiber
  ; lev_fiber_csexp
  jsonrpc
  spawn
  lsp
  ; lsp_fiber
  cmarkit
  ; odoc_parser
  ppx_yojson_conv_lib
  re
  stdune
  ordering
  csexp
  yojson
  dune-rpc
  ocamlformat-rpc-lib
  ocamlc-loc
  base)
 (lint
  (pps ppx_yojson_conv))
 (instrumentation
  (backend bisect_ppx)))

(include_subdirs unqualified)