val explicit_substitutions : bool ref
val print_explicit_substitutions : bool ref
val unroll_coherences : bool ref
val verbosity : int ref
val use_builtins : bool ref
val pretty_printing : bool ref
val implicit_suspension : bool ref
val keep_going : bool ref
val debug : bool ref
val postprocess : bool ref
