(* open Common *)
(* module CoreSignature = Core *)

(* exception IsCoh *)
(* exception IsObj *)
(* exception MetaVariable *)

(* module Make (Theory : Theory.S) = struct *)
(*   module InnerKernel = Kernel.Make (Theory) *)
(*   module Coh = InnerKernel.Coh *)

(*   (\** Operations on terms. *\) *)
(*   module rec Tm : sig *)
(*     type expr = *)
(*       [ `Var of Var.t | `Coh of Coh.t * B.Sub.t | `App of Tm.t * B.Sub.t ] *)

(*     and t = private { *)
(*       ty : B.Ty.t; *)
(*       e : expr; *)
(*       unchecked : (Coh.t, t) tm; *)
(*       mutable developped : (Coh.t, t) tm option; *)
(*       name : pp_data option; *)
(*     } *)

(*     (\* Data extraction *\) *)
(*     val to_var : t -> Var.t *)
(*     val ty : t -> (Coh.t, Tm.t) ty *)
(*     val ctx : t -> (Coh.t, Tm.t) ctx *)
(*     val forget : t -> (Coh.t, Tm.t) tm *)
(*     val constr : t -> (Coh.t, Tm.t) constr *)
(*     val name : t -> string option *)
(*     val full_name : t -> string option *)
(*     val func_data : t -> (Var.t * int) list list option *)
(*     val pp_data : t -> pp_data option *)
(*     val to_string : t -> string *)

(*     (\* Production of terms *\) *)
(*     val of_coh : Coh.t -> t *)

(*     val check_in_ctx : *)
(*       B.Ctx.t -> ?ty:B.Ty.t -> ?name:pp_data -> (Coh.t, Tm.t) tm -> t *)

(*     val check : *)
(*       (Coh.t, Tm.t) ctx -> *)
(*       ?ty:(Coh.t, Tm.t) ty -> *)
(*       ?name:pp_data -> *)
(*       (Coh.t, Tm.t) tm -> *)
(*       t *)

(*     val apply_sub : t -> B.Sub.t -> t *)
(*     val preimage : t -> B.Sub.t -> t *)
(*     val develop : t -> (Coh.t, Tm.t) tm *)

(*     val apply : *)
(*       ((Coh.t, Tm.t) ctx -> (Coh.t, Tm.t) ctx) -> *)
(*       ((Coh.t, Tm.t) tm -> (Coh.t, Tm.t) tm) -> *)
(*       (pp_data -> pp_data) -> *)
(*       t -> *)
(*       t * (Coh.t, Tm.t) sub *)

(*     val is_equal : t -> t -> bool *)
(*   end = struct *)
(*     open Syntax.Make (Core) *)
(*     module Ty = B.Ty *)
(*     module Ctx = B.Ctx *)
(*     module Sub = B.Sub *)

(*     type expr = *)
(*       [ `Var of Var.t | `Coh of Coh.t * B.Sub.t | `App of Tm.t * B.Sub.t ] *)

(*     type t = { *)
(*       ty : Ty.t; *)
(*       e : expr; *)
(*       unchecked : tm; *)
(*       mutable developped : tm option; *)
(*       name : pp_data option; *)
(*     } *)

(*     let ty t = t.ty.unchecked *)
(*     let tbl : (B.Ctx.t * tm, Tm.t) Hashtbl.t = Hashtbl.create 7829 *)
(*     let forget tm = tm.unchecked *)
(*     let constr tm = (forget tm, ty tm) *)

(*     let check_in_ctx c ?ty ?name t = *)
(*       Io.info ~v:5 *)
(*         (lazy *)
(*           (Printf.sprintf "building kernel term %s in context %s" *)
(*              (Printing.tm_to_string t) (Ctx.to_string c))); *)
(*       let tm = *)
(*         match Hashtbl.find_opt tbl (c, t) with *)
(*         | Some tm -> tm *)
(*         | None -> ( *)
(*             match t with *)
(*             | Var x -> *)
(*                 let e, ty = (`Var x, Ty.check c (Ctx.ty_var c x).unchecked) in *)
(*                 { ty; e; unchecked = t; developped = Some t; name } *)
(*             | Meta_tm _ -> raise MetaVariable *)
(*             | Coh (coh, s) -> *)
(*                 let sub = Sub.check_to_ps c s (Coh.ps coh) in *)
(*                 let e, ty = (`Coh (coh, sub), Ty.apply_sub (Coh.ty coh) sub) in *)
(*                 let tm = { ty; e; unchecked = t; developped = Some t; name } in *)
(*                 Hashtbl.add tbl (c, t) tm; *)
(*                 tm *)
(*             | App (u, s) -> *)
(*                 let ty = u.ty in *)
(*                 let sub = Sub.check c s ty.c in *)
(*                 let e, ty = (`App (u, sub), Ty.apply_sub ty sub) in *)
(*                 let tm = { ty; e; unchecked = t; developped = None; name } in *)
(*                 Hashtbl.add tbl (c, t) tm; *)
(*                 tm) *)
(*       in *)
(*       match ty with *)
(*       | None -> tm *)
(*       | Some ty -> *)
(*           Ty.check_equal ty tm.ty; *)
(*           tm *)

(*     let check c ?ty ?name tm = *)
(*       let c = Ctx.check c in *)
(*       let ty = Option.map (Ty.check c) ty in *)
(*       check_in_ctx c ?ty ?name tm *)

(*     let develop tm = *)
(*       match tm.developped with *)
(*       | Some t -> t *)
(*       | None -> *)
(*           let dev = *)
(*             match tm.e with *)
(*             | `Var _ | `Coh (_, _) -> tm.unchecked *)
(*             | `App (t, s) -> *)
(*                 let dt = Tm.develop t in *)
(*                 let s = s.unchecked in *)
(*                 Unchecked.tm_apply_sub dt s *)
(*           in *)
(*           tm.developped <- Some dev; *)
(*           dev *)

(*     let to_var tm = *)
(*       match tm.e with *)
(*       | `Var v -> v *)
(*       | `Coh _ -> raise IsCoh *)
(*       | `App _ -> ( *)
(*           match develop tm with *)
(*           | Var v -> v *)
(*           | Coh _ -> raise IsCoh *)
(*           | App _ | Meta_tm _ -> assert false) *)

(*     let apply_sub t (sub : B.Sub.t) = *)
(*       Ctx.check_equal sub.tgt t.ty.c; *)
(*       let c = sub.src in *)
(*       let ty = Ty.apply_sub t.ty sub in *)
(*       let t = Unchecked.tm_apply_sub (forget t) sub.unchecked in *)
(*       check_in_ctx c ~ty t *)

(*     let preimage t (sub : B.Sub.t) = *)
(*       Ctx.check_equal sub.src t.ty.c; *)
(*       let c = sub.tgt in *)
(*       let t = Unchecked.tm_sub_preimage (forget t) sub.unchecked in *)
(*       check_in_ctx c t *)

(*     let is_equal t1 t2 = *)
(*       Ctx.is_equal t1.ty.c t2.ty.c *)
(*       && Equality.is_equal_tm t1.unchecked t2.unchecked *)

(*     let apply fun_ctx fun_tm fun_pp_data tm = *)
(*       let c = fun_ctx (Ctx.forget tm.ty.c) in *)
(*       let db_sub = Unchecked.db_level_sub_inv c in *)
(*       let c, _, _ = Unchecked.db_levels c in *)
(*       let c = Ctx.check c in *)
(*       let newexp = Unchecked.tm_apply_sub (fun_tm (forget tm)) db_sub in *)
(*       let name = *)
(*         Option.map *)
(*           (fun pp_data -> *)
(*             Display_maps.pp_data_rename (fun_pp_data pp_data) db_sub) *)
(*           tm.name *)
(*       in *)
(*       (check_in_ctx c ?name newexp, db_sub) *)

(*     let ctx t = Ctx.forget t.ty.c *)
(*     let name t = Option.map Printing.pp_data_to_string t.name *)
(*     let full_name t = Option.map Printing.full_name t.name *)
(*     let func_data t = Option.map (fun (_, _, f) -> f) t.name *)
(*     let pp_data t = t.name *)

(*     let to_string t = *)
(*       match full_name t with *)
(*       | Some name -> name *)
(*       | None -> Printing.tm_to_string (forget t) *)

(*     let of_coh coh = *)
(*       let ps, _, pp_data = Coh.forget coh in *)
(*       let id = Unchecked.identity_ps ps in *)
(*       let ctx = Unchecked.ps_to_ctx ps in *)
(*       check_in_ctx (Ctx.check ctx) ~name:pp_data (Coh (coh, id)) *)
(*   end *)

(*   and Ty : sig *)
(*     type t *)
(*   end = struct end *)

(*   and Core : *)
(*     (CoreSignature.S *)
(*       with type Ty.t = Ty.t *)
(*       with type Coh.t = Coh.t *)
(*       with type Coh.innertm = InnerKernel.Tm.t *)
(*       with type Tm.t = Tm.t) = struct *)
(*     module PS = PS *)
(*     module Ty = Ty *)
(*     module Tm = Tm *)
(*     module Coh = Coh *)
(*   end *)

(*   and B : sig *)
(*     exception IsObj *)
(*     exception IsCoh *)
(*     exception InvalidSubTarget of string * string *)
(*     exception MetaVariable *)

(*     module rec Sub : sig *)
(*       type t = private { *)
(*         list : Tm.t list; *)
(*         src : Ctx.t; *)
(*         tgt : Ctx.t; *)
(*         unchecked : (Coh.t, Tm.t) sub; *)
(*       } *)

(*       val check : Ctx.t -> (Coh.t, Tm.t) sub -> Ctx.t -> t *)
(*       val check_to_ps : Ctx.t -> (Coh.t, Tm.t) sub_ps -> PS.t -> Sub.t *)
(*     end *)

(*     and Ctx : sig *)
(*       type t = private { *)
(*         c : (Var.t * Ty.t) list; *)
(*         unchecked : (Coh.t, Tm.t) ctx; *)
(*       } *)

(*       val to_string : t -> string *)
(*       val ty_var : t -> Var.t -> Ty.t *)
(*       val domain : t -> Var.t list *)
(*       val forget : t -> (Coh.t, Tm.t) ctx *)
(*       val check : (Coh.t, Tm.t) ctx -> t *)
(*       val is_equal : t -> t -> bool *)
(*       val check_equal : t -> t -> unit *)
(*     end *)

(*     and PS : sig *)
(*       exception Invalid *)

(*       type t = ps *)

(*       val to_string : t -> string *)
(*       val mk : Ctx.t -> t *)
(*       val bdry : t -> t *)
(*       val source : t -> Sub.t *)
(*       val target : t -> Sub.t *)
(*       val is_equal : t -> t -> bool *)
(*     end *)

(*     and Ty : sig *)
(*       type t = private { c : Ctx.t; e : expr; unchecked : (Coh.t, Tm.t) ty } *)
(*       and expr = Obj | Arr of t * Tm.t * Tm.t *)

(*       val to_string : t -> string *)
(*       val is_equal : t -> t -> bool *)
(*       val check_equal : t -> t -> unit *)
(*       val morphism : Tm.t -> Tm.t -> Ty.t *)
(*       val check : Ctx.t -> (Coh.t, Tm.t) ty -> t *)
(*       val apply_sub : t -> Sub.t -> t *)
(*       val dim : t -> int *)
(*     end *)
(*   end = *)
(*     Builder.Make (Core) *)

(*   module Ty = B.Ty *)
(*   module Ctx = B.Ctx *)
(*   module Sub = B.Sub *)
(*   module PS = B.PS *)
(*   include Syntax.Make (Core) *)

(*   let check check_fn name = *)
(*     let v = 2 in *)
(*     let fname = if !Settings.verbosity >= v then Lazy.force name else "" in *)
(*     Io.info ~v (lazy ("checking " ^ fname)); *)
(*     try check_fn () with *)
(*     | NotEqual (s1, s2) -> *)
(*         Error.untypable *)
(*           (if !Settings.verbosity >= v then fname else Lazy.force name) *)
(*           (Printf.sprintf "%s and %s are not equal" s1 s2) *)
(*     | B.InvalidSubTarget (s, tgt) -> *)
(*         Error.untypable *)
(*           (if !Settings.verbosity >= v then fname else Lazy.force name) *)
(*           (Printf.sprintf "substitution %s does not apply from context %s" s tgt) *)
(*     | Error.UnknownId s -> *)
(*         Error.untypable *)
(*           (if !Settings.verbosity >= v then fname else Lazy.force name) *)
(*           (Printf.sprintf "unknown identifier :%s" s) *)
(*     | MetaVariable -> *)
(*         Error.incomplete_constraints *)
(*           (if !Settings.verbosity >= v then fname else Lazy.force name) *)

(*   let check_type ctx a = *)
(*     let ty = lazy ("type: " ^ Printing.ty_to_string a) in *)
(*     check (fun () -> Ty.check ctx a) ty *)

(*   let check_term ctx ?ty ?name t = *)
(*     let ty = Option.map (check_type ctx) ty in *)
(*     let tm = lazy ("term: " ^ Printing.tm_to_string t) in *)
(*     check (fun () -> Tm.check_in_ctx ctx ?ty ?name t) tm *)

(*   let check_constr ?name ctx constr = *)
(*     let ctx = Ctx.check ctx in *)
(*     let t, ty = constr in *)
(*     let ty = if !Settings.debug then None else Some ty in *)
(*     check_term ctx ?ty ?name t *)

(*   let check_coh ps ty pp_data = *)
(*     let c = lazy ("coherence: " ^ Printing.pp_data_to_string pp_data) in *)
(*     check (fun () -> Coh.check ps ty pp_data) c *)

(*   let check_sub src s tgt = *)
(*     ignore @@ Sub.check (Ctx.check src) s (Ctx.check tgt) *)
(* end *)
